name: nightly-netlify-build

on:
  schedule:
    - cron: "0 3 * * Sun"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: trigger netlify build
        run: |
          curl -X POST -d '{}' https://api.netlify.com/build_hooks/641843587aee3b2baf8bba24
